---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        version: '26'
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: backend
        image: thadhojunyi/eresource:backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30002
    protocol: TCP
  selector:
    app: backend
  type: NodePort
